"""add_phone_cpf_to_owners

Revision ID: e8f3a1b2c4d5
Revises: 4494330ffac1
Create Date: 2025-02-11 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8f3a1b2c4d5'
down_revision: Union[str, Sequence[str], None] = '4494330ffac1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owners', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('owners', sa.Column('cpf', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('owners', 'cpf')
    op.drop_column('owners', 'phone')
    # ### end Alembic commands ###
