"""add_motive_to_patients

Revision ID: dac8969e0ed1
Revises: 76ee4f06c72d
Create Date: 2025-12-27 23:05:25.650965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dac8969e0ed1'
down_revision: Union[str, Sequence[str], None] = '76ee4f06c72d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('motive', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'motive')
    # ### end Alembic commands ###
