export const clerkLocalization = {
  dividerText: "ou",
  formButtonPrimary: "Continuar",
  formButtonReset: "Cancelar",
  formButtonPrimary__verify: "Verificar",
  formFieldLabel__emailAddress: "Endereço de e-mail",
  formFieldLabel__emailAddresses: "Endereços de e-mail",
  formFieldLabel__phoneNumber: "Telefone",
  formFieldLabel__username: "Nome de usuário",
  formFieldLabel__emailAddress_username: "E-mail ou nome de usuário",
  formFieldLabel__password: "Senha",
  formFieldLabel__firstName: "Primeiro nome",
  formFieldLabel__lastName: "Sobrenome",
  formFieldInputPlaceholder__emailAddress: "Digite seu e-mail",
  formFieldInputPlaceholder__phoneNumber: "Digite seu telefone",
  formFieldInputPlaceholder__username: "Digite seu nome de usuário",
  formFieldInputPlaceholder__emailAddress_username:
    "Digite seu e-mail ou nome de usuário",
  formFieldInputPlaceholder__password: "Digite sua senha",
  formFieldInputPlaceholder__firstName: "Digite seu primeiro nome",
  formFieldInputPlaceholder__lastName: "Digite seu sobrenome",
  formFieldAction__forgotPassword: "Esqueceu sua senha?",
  socialButtonsBlockButton: "Continuar com {{provider}}",
  socialButtonsBlockButtonManyInView: "Continuar com {{provider}}",
  footerActionText: "Não tem uma conta?",
  footerActionLink: "Criar conta",
  signIn: {
    start: {
      title: "Entrar",
      subtitle: "Acesse sua conta para continuar no VetData.",
      actionText: "Ainda não tem uma conta?",
      actionLink: "Criar conta",
      actionLink__use_email: "Usar e-mail",
      actionLink__use_phone: "Usar telefone",
      actionLink__use_username: "Usar nome de usuário",
      actionLink__use_email_username: "Usar e-mail ou nome de usuário",
      actionLink__use_passkey: "Usar passkey",
    },
    password: {
      title: "Digite sua senha",
      subtitle: "Confirme sua identidade para acessar a plataforma.",
      actionLink: "Usar outro método",
    },
    forgotPassword: {
      title: "Redefinir senha",
      subtitle: "Enviaremos instruções para recuperar o acesso.",
      subtitle_email: "Enviaremos instruções para seu e-mail.",
      subtitle_phone: "Enviaremos um código para seu telefone.",
      formTitle: "Verifique seu método",
      resendButton: "Reenviar",
    },
    emailCode: {
      title: "Verifique seu e-mail",
      subtitle: "Digite o código enviado para continuar.",
      formTitle: "Código de verificação",
      resendButton: "Reenviar código",
    },
    phoneCode: {
      title: "Verifique seu telefone",
      subtitle: "Digite o código enviado para continuar.",
      formTitle: "Código de verificação",
      resendButton: "Reenviar código",
    },
    resetPassword: {
      title: "Defina uma nova senha",
      formButtonPrimary: "Salvar nova senha",
      successMessage: "Senha atualizada com sucesso.",
      requiredMessage: "Defina uma nova senha para continuar.",
    },
  },
  signUp: {
    start: {
      title: "Criar conta",
      subtitle: "Cadastre sua equipe para começar a usar o VetData.",
      actionText: "Já possui conta?",
      actionLink: "Entrar",
      actionLink__use_phone: "Usar telefone",
      actionLink__use_email: "Usar e-mail",
    },
    continue: {
      title: "Complete seu cadastro",
      subtitle: "Falta pouco para ativar o acesso da clínica.",
      actionText: "Já possui conta?",
      actionLink: "Entrar",
    },
    emailCode: {
      title: "Confirme seu e-mail",
      subtitle: "Digite o código enviado para concluir o cadastro.",
      formTitle: "Código de verificação",
      formSubtitle: "Verifique sua caixa de entrada para continuar.",
      resendButton: "Reenviar código",
    },
    phoneCode: {
      title: "Confirme seu telefone",
      subtitle: "Digite o código enviado para concluir o cadastro.",
      formTitle: "Código de verificação",
      formSubtitle: "Verifique as mensagens para continuar.",
      resendButton: "Reenviar código",
    },
  },
  userProfile: {
    mobileButton__menu: "Menu",
    formButtonPrimary__continue: "Continuar",
    formButtonPrimary__save: "Salvar",
    formButtonPrimary__finish: "Concluir",
    formButtonPrimary__remove: "Remover",
    formButtonPrimary__add: "Adicionar",
    formButtonReset: "Cancelar",
    navbar: {
      title: "Conta",
      description: "Gerencie seus dados, acessos e segurança.",
      account: "Perfil",
      security: "Segurança",
      billing: "Faturamento",
      apiKeys: "Chaves de API",
    },
    start: {
      headerTitle__account: "Perfil",
      headerTitle__security: "Segurança",
      profileSection: {
        title: "Perfil",
        primaryButton: "Atualizar perfil",
      },
      usernameSection: {
        title: "Nome de usuário",
        primaryButton__updateUsername: "Atualizar nome de usuário",
        primaryButton__setUsername: "Definir nome de usuário",
      },
      emailAddressesSection: {
        title: "Endereços de e-mail",
        primaryButton: "Adicionar e-mail",
        detailsAction__primary: "Principal",
        detailsAction__nonPrimary: "Tornar principal",
        detailsAction__unverified: "Verificar",
        destructiveAction: "Remover",
      },
      phoneNumbersSection: {
        title: "Telefones",
        primaryButton: "Adicionar telefone",
        detailsAction__primary: "Principal",
        detailsAction__nonPrimary: "Tornar principal",
        detailsAction__unverified: "Verificar",
        destructiveAction: "Remover",
      },
      connectedAccountsSection: {
        title: "Contas conectadas",
        primaryButton: "Conectar conta",
        actionLabel__connectionFailed: "Reconectar",
        actionLabel__reauthorize: "Reconectar",
        subtitle__disconnected: "A conexão foi interrompida.",
        destructiveActionTitle: "Remover conta conectada",
      },
      enterpriseAccountsSection: {
        title: "Contas corporativas",
      },
      passwordSection: {
        title: "Senha",
        primaryButton__updatePassword: "Alterar senha",
        primaryButton__setPassword: "Definir senha",
      },
      passkeysSection: {
        title: "Passkeys",
        primaryButton: "Adicionar passkey",
        menuAction__rename: "Renomear",
        menuAction__destructive: "Remover",
      },
      mfaSection: {
        title: "Autenticação em dois fatores",
        primaryButton: "Ativar autenticação",
      },
      activeDevicesSection: {
        title: "Dispositivos ativos",
        destructiveAction: "Encerrar sessão",
      },
      dangerSection: {
        title: "Zona de risco",
        deleteAccountButton: "Excluir conta",
      },
    },
    profilePage: {
      title: "Atualizar perfil",
      imageFormTitle: "Foto de perfil",
      imageFormSubtitle: "Envie uma imagem para representar sua conta.",
      imageFormDestructiveActionSubtitle: "Remova a imagem atual do perfil.",
      fileDropAreaHint: "Arraste um arquivo aqui ou selecione uma imagem",
      readonly: "Somente leitura",
      successMessage: "Perfil atualizado com sucesso.",
    },
    usernamePage: {
      successMessage: "Nome de usuário atualizado com sucesso.",
      title__set: "Definir nome de usuário",
      title__update: "Atualizar nome de usuário",
    },
    emailAddressPage: {
      title: "Gerenciar e-mail",
      verifyTitle: "Verificar e-mail",
      formHint: "Confirme o endereço para usá-lo na conta.",
    },
    phoneNumberPage: {
      title: "Gerenciar telefone",
      verifyTitle: "Verificar telefone",
      formHint: "Confirme o número para habilitar notificações e recuperação.",
    },
  },
} as const;
